/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configGet } from "../../funcs/configGet.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$configGet: ToolDefinition = {
  name: "config-get",
  description: `Get current configuration`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await configGet(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
