/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configUpdate } from "../../funcs/configUpdate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.UpdateConfigDto$inboundSchema,
};

export const tool$configUpdate: ToolDefinition<typeof args> = {
  name: "config-update",
  description: `Update configuration`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await configUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
