/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesUpload } from "../../funcs/filesUpload.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.FileUploadDto$inboundSchema,
};

export const tool$filesUpload: ToolDefinition<typeof args> = {
  name: "files-upload",
  description: `Upload a file

Upload a file for later processing. The system stores the file and provides a unique identifier for future reference.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filesUpload(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
