/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesDownload } from "../../funcs/filesDownload.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DownloadFileRequest$inboundSchema,
};

export const tool$filesDownload: ToolDefinition<typeof args> = {
  name: "files-download",
  description: `Download a file`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filesDownload(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
