/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesGetInfo } from "../../funcs/filesGetInfo.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetFileInfoRequest$inboundSchema,
};

export const tool$filesGetInfo: ToolDefinition<typeof args> = {
  name: "files-get-info",
  description: `Get information about a specific file`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filesGetInfo(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
