/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { humanLayerApprove } from "../../funcs/humanLayerApprove.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ApproveRequestRequest$inboundSchema,
};

export const tool$humanLayerApprove: ToolDefinition<typeof args> = {
  name: "human-layer-approve",
  description: `Approve a pending human layer request`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await humanLayerApprove(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
