/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { humanLayerGetRequests } from "../../funcs/humanLayerGetRequests.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$humanLayerGetRequests: ToolDefinition = {
  name: "human-layer-get-requests",
  description: `Get all pending human layer requests`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await humanLayerGetRequests(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
