/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { irisArtifactsDownloadFolder } from "../../funcs/irisArtifactsDownloadFolder.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DownloadArtifactFolderRequest$inboundSchema,
};

export const tool$irisArtifactsDownloadFolder: ToolDefinition<typeof args> = {
  name: "iris-artifacts-download-folder",
  description: `Download a directory of artifacts as a zip file`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await irisArtifactsDownloadFolder(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
