/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { irisArtifactsList } from "../../funcs/irisArtifactsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListArtifactsRequest$inboundSchema,
};

export const tool$irisArtifactsList: ToolDefinition<typeof args> = {
  name: "iris-artifacts-list",
  description: `List artifacts in a directory within the .iris folder`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await irisArtifactsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
