/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { irisArtifactsDownloadFile } from "../../funcs/irisArtifactsDownloadFile.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DownloadArtifactFileRequest$inboundSchema,
};

export const tool$irisArtifactsDownloadFile: ToolDefinition<typeof args> = {
  name: "iris-artifacts-download-file",
  description: `Download a file artifact from the .iris folder`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await irisArtifactsDownloadFile(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
