/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { operatorsGetTypes } from "../../funcs/operatorsGetTypes.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$operatorsGetTypes: ToolDefinition = {
  name: "operators-get-types",
  description: `Get available operator types

Returns a list of available automation operator types that autonomous agents can use to interact with applications. The system supports both browser-based operators for web automation and computer operators for native desktop application automation, giving agents the flexibility to work across different environments.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await operatorsGetTypes(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
