/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rpaGetStatus } from "../../funcs/rpaGetStatus.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetExecutionStatusRequest$inboundSchema,
};

export const tool$rpaGetStatus: ToolDefinition<typeof args> = {
  name: "rpa-get-status",
  description: `Get status of an RPA execution

Returns the current status and progress of an RPA execution.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await rpaGetStatus(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
