/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rpaStopExecution } from "../../funcs/rpaStopExecution.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.StopExecutionRequest$inboundSchema,
};

export const tool$rpaStopExecution: ToolDefinition<typeof args> = {
  name: "rpa-stop-execution",
  description: `Stop an ongoing RPA execution

Stops a running RPA execution and releases resources.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await rpaStopExecution(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
