/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rpaStartExecution } from "../../funcs/rpaStartExecution.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.StartRpaExecutionDto$inboundSchema,
};

export const tool$rpaStartExecution: ToolDefinition<typeof args> = {
  name: "rpa-start-execution",
  description: `Start RPA execution from a recording

Initiates an automated execution of actions captured in a recording. This endpoint enables precise replay of previously recorded tasks with exact timing and interaction patterns. The system faithfully reproduces the recorded sequence, maintaining the original intent and workflow across different execution environments.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await rpaStartExecution(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
