/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { videosDeleteRecording } from "../../funcs/videosDeleteRecording.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteRecordingRequest$inboundSchema,
};

export const tool$videosDeleteRecording: ToolDefinition<typeof args> = {
  name: "videos-delete-recording",
  description: `Delete recording by ID

Permanently deletes a recording and all associated files. This operation cannot be undone. It removes all frames, captions, metadata, and the generated video file.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await videosDeleteRecording(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
