/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { videosDownload } from "../../funcs/videosDownload.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DownloadRecordingRequest$inboundSchema,
};

export const tool$videosDownload: ToolDefinition<typeof args> = {
  name: "videos-download",
  description: `Download recording as ZIP file

Downloads a recording as a ZIP archive containing all frames, captions, and metadata. This is useful for backup purposes or offline processing. For normal video playback, use the video endpoint instead.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await videosDownload(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
