/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { videoStreamProcessed } from "../../funcs/videoStreamProcessed.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.StreamProcessedVideoRequest$inboundSchema,
};

export const tool$videoStreamProcessed: ToolDefinition<typeof args> = {
  name: "video-stream-processed",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await videoStreamProcessed(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
