/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { videoGetAnalysisResults } from "../../funcs/videoGetAnalysisResults.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAnalysisResultsRequest$inboundSchema,
};

export const tool$videoGetAnalysisResults: ToolDefinition<typeof args> = {
  name: "video-get-analysis-results",
  description: `Get analysis results for a video`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await videoGetAnalysisResults(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
