/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { videoEditingUpdateCaption } from "../../funcs/videoEditingUpdateCaption.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateCaptionRequest$inboundSchema,
};

export const tool$videoEditingUpdateCaption: ToolDefinition<typeof args> = {
  name: "video-editing-update-caption",
  description: `Update caption for a frame

Updates the caption text for a specific frame`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await videoEditingUpdateCaption(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
