/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { videosGetFramesAndCaptions } from "../../funcs/videosGetFramesAndCaptions.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetFramesAndCaptionsRequest$inboundSchema,
};

export const tool$videosGetFramesAndCaptions: ToolDefinition<typeof args> = {
  name: "videos-get-frames-and-captions",
  description: `Get frames and captions for editing

Returns all frames and their associated captions for a recording to be edited`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await videosGetFramesAndCaptions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
