/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { videoEditingDeleteFrame } from "../../funcs/videoEditingDeleteFrame.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteFrameRequest$inboundSchema,
};

export const tool$videoEditingDeleteFrame: ToolDefinition<typeof args> = {
  name: "video-editing-delete-frame",
  description: `Delete a frame

Deletes a specific frame from a recording and updates captions accordingly`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await videoEditingDeleteFrame(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
