/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { videosGetRecordingData } from "../../funcs/videosGetRecordingData.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetRecordingVideoDataRequest$inboundSchema,
};

export const tool$videosGetRecordingData: ToolDefinition<typeof args> = {
  name: "videos-get-recording-data",
  description: `Get video data for a specific recording

Returns the raw frames and captions for a specific recording. This endpoint is primarily used for replaying recordings in the UI.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await videosGetRecordingData(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
