/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { videoEditingRegenerate } from "../../funcs/videoEditingRegenerate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RegenerateVideoRequest$inboundSchema,
};

export const tool$videoEditingRegenerate: ToolDefinition<typeof args> = {
  name: "video-editing-regenerate",
  description: `Regenerate video after edits

Regenerates the video file after frames or captions have been edited`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await videoEditingRegenerate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
