/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { videosGetThumbnail } from "../../funcs/videosGetThumbnail.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetRecordingThumbnailRequest$inboundSchema,
};

export const tool$videosGetThumbnail: ToolDefinition<typeof args> = {
  name: "videos-get-thumbnail",
  description: `Get recording thumbnail

Returns the thumbnail image for a recording as a PNG file. This is typically the first frame of the recording.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await videosGetThumbnail(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
