/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { videosGetCurrentSessionData } from "../../funcs/videosGetCurrentSessionData.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$videosGetCurrentSessionData: ToolDefinition = {
  name: "videos-get-current-session-data",
  description: `Get video data for current session

Returns the raw frames and captions for the current active session. This endpoint is primarily used for diagnostic purposes or custom video processing. Most clients should use the generated video file instead of raw frames.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await videosGetCurrentSessionData(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
