/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configGet } from "../funcs/configGet.js";
import { configUpdate } from "../funcs/configUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Config extends ClientSDK {
  /**
   * Get current configuration
   */
  async get(
    options?: RequestOptions,
  ): Promise<components.ConfigResponseDto> {
    return unwrapAsync(configGet(
      this,
      options,
    ));
  }

  /**
   * Update configuration
   */
  async update(
    request: components.UpdateConfigDto,
    options?: RequestOptions,
  ): Promise<components.ConfigResponseDto> {
    return unwrapAsync(configUpdate(
      this,
      request,
      options,
    ));
  }
}
