/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { humanLayerApprove } from "../funcs/humanLayerApprove.js";
import { humanLayerGetRequests } from "../funcs/humanLayerGetRequests.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class HumanLayer extends ClientSDK {
  /**
   * Get all pending human layer requests
   */
  async getRequests(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(humanLayerGetRequests(
      this,
      options,
    ));
  }

  /**
   * Approve a pending human layer request
   */
  async approve(
    request: operations.ApproveRequestRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(humanLayerApprove(
      this,
      request,
      options,
    ));
  }
}
