/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { irisArtifactsDownloadFile } from "../funcs/irisArtifactsDownloadFile.js";
import { irisArtifactsDownloadFolder } from "../funcs/irisArtifactsDownloadFolder.js";
import { irisArtifactsList } from "../funcs/irisArtifactsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class IrisArtifacts extends ClientSDK {
  /**
   * List artifacts in a directory within the .iris folder
   */
  async list(
    request: operations.ListArtifactsRequest,
    options?: RequestOptions,
  ): Promise<components.ArtifactsContentDto> {
    return unwrapAsync(irisArtifactsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Download a file artifact from the .iris folder
   */
  async downloadFile(
    request: operations.DownloadArtifactFileRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(irisArtifactsDownloadFile(
      this,
      request,
      options,
    ));
  }

  /**
   * Download a directory of artifacts as a zip file
   */
  async downloadFolder(
    request: operations.DownloadArtifactFolderRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(irisArtifactsDownloadFolder(
      this,
      request,
      options,
    ));
  }
}
