/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { operatorsGetTypes } from "../funcs/operatorsGetTypes.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Operators extends ClientSDK {
  /**
   * Get available operator types
   *
   * @remarks
   * Returns a list of available automation operator types that autonomous agents can use to interact with applications. The system supports both browser-based operators for web automation and computer operators for native desktop application automation, giving agents the flexibility to work across different environments.
   */
  async getTypes(
    options?: RequestOptions,
  ): Promise<components.OperatorTypesDto> {
    return unwrapAsync(operatorsGetTypes(
      this,
      options,
    ));
  }
}
