/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Config } from "./config.js";
import { Files } from "./files.js";
import { HumanLayer } from "./humanlayer.js";
import { IrisArtifacts } from "./irisartifacts.js";
import { Operators } from "./operators.js";
import { Rpa } from "./rpa.js";
import { Video } from "./video.js";
import { VideoEditing } from "./videoediting.js";
import { Videos } from "./videos.js";

export class IrisSDK extends ClientSDK {
  private _config?: Config;
  get config(): Config {
    return (this._config ??= new Config(this._options));
  }

  private _videos?: Videos;
  get videos(): Videos {
    return (this._videos ??= new Videos(this._options));
  }

  private _videoEditing?: VideoEditing;
  get videoEditing(): VideoEditing {
    return (this._videoEditing ??= new VideoEditing(this._options));
  }

  private _operators?: Operators;
  get operators(): Operators {
    return (this._operators ??= new Operators(this._options));
  }

  private _rpa?: Rpa;
  get rpa(): Rpa {
    return (this._rpa ??= new Rpa(this._options));
  }

  private _video?: Video;
  get video(): Video {
    return (this._video ??= new Video(this._options));
  }

  private _files?: Files;
  get files(): Files {
    return (this._files ??= new Files(this._options));
  }

  private _humanLayer?: HumanLayer;
  get humanLayer(): HumanLayer {
    return (this._humanLayer ??= new HumanLayer(this._options));
  }

  private _irisArtifacts?: IrisArtifacts;
  get irisArtifacts(): IrisArtifacts {
    return (this._irisArtifacts ??= new IrisArtifacts(this._options));
  }
}
