/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the iris-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx configGet.example.ts
 */

import { IrisSDK } from "iris-sdk";

const irisSDK = new IrisSDK();

async function main() {
  const result = await irisSDK.config.get();

  console.log(result);
}

main().catch(console.error);
