workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Zenobia Intelligent Automation Platform API:
        inputs:
            - location: https://raw.githubusercontent.com/pokemonlabs/iris.release/refs/heads/main/openapi.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/iris-ed/main/zenobia-intelligent-automation-platform-api
targets:
    iris-sdk:
        target: typescript
        source: Zenobia Intelligent Automation Platform API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/iris-ed/main/zenobia-intelligent-automation-platform-api-typescript-code-samples
            blocking: false
