/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApproveRequestRequest = {
  requestId: string;
};

/** @internal */
export const ApproveRequestRequest$inboundSchema: z.ZodType<
  ApproveRequestRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  requestId: z.string(),
});
/** @internal */
export type ApproveRequestRequest$Outbound = {
  requestId: string;
};

/** @internal */
export const ApproveRequestRequest$outboundSchema: z.ZodType<
  ApproveRequestRequest$Outbound,
  z.ZodTypeDef,
  ApproveRequestRequest
> = z.object({
  requestId: z.string(),
});

export function approveRequestRequestToJSON(
  approveRequestRequest: ApproveRequestRequest,
): string {
  return JSON.stringify(
    ApproveRequestRequest$outboundSchema.parse(approveRequestRequest),
  );
}
export function approveRequestRequestFromJSON(
  jsonString: string,
): SafeParseResult<ApproveRequestRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApproveRequestRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApproveRequestRequest' from JSON`,
  );
}
