/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteRecordingRequest = {
  /**
   * The ID of the recording to delete
   */
  id: string;
};

/** @internal */
export const DeleteRecordingRequest$inboundSchema: z.ZodType<
  DeleteRecordingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type DeleteRecordingRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteRecordingRequest$outboundSchema: z.ZodType<
  DeleteRecordingRequest$Outbound,
  z.ZodTypeDef,
  DeleteRecordingRequest
> = z.object({
  id: z.string(),
});

export function deleteRecordingRequestToJSON(
  deleteRecordingRequest: DeleteRecordingRequest,
): string {
  return JSON.stringify(
    DeleteRecordingRequest$outboundSchema.parse(deleteRecordingRequest),
  );
}
export function deleteRecordingRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteRecordingRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteRecordingRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteRecordingRequest' from JSON`,
  );
}
