/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteRecordingRequest = {
  /**
   * The ID of the recording to delete
   */
  id: string;
};

/** @internal */
export const DeleteRecordingRequest$inboundSchema: z.ZodType<
  DeleteRecordingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteRecordingRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteRecordingRequest$outboundSchema: z.ZodType<
  DeleteRecordingRequest$Outbound,
  z.ZodTypeDef,
  DeleteRecordingRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteRecordingRequest$ {
  /** @deprecated use `DeleteRecordingRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteRecordingRequest$inboundSchema;
  /** @deprecated use `DeleteRecordingRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteRecordingRequest$outboundSchema;
  /** @deprecated use `DeleteRecordingRequest$Outbound` instead. */
  export type Outbound = DeleteRecordingRequest$Outbound;
}

export function deleteRecordingRequestToJSON(
  deleteRecordingRequest: DeleteRecordingRequest,
): string {
  return JSON.stringify(
    DeleteRecordingRequest$outboundSchema.parse(deleteRecordingRequest),
  );
}

export function deleteRecordingRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteRecordingRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteRecordingRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteRecordingRequest' from JSON`,
  );
}
