/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DownloadArtifactFolderRequest = {
  /**
   * Path to the directory relative to .iris folder
   */
  path: string;
};

/** @internal */
export const DownloadArtifactFolderRequest$inboundSchema: z.ZodType<
  DownloadArtifactFolderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  path: z.string(),
});

/** @internal */
export type DownloadArtifactFolderRequest$Outbound = {
  path: string;
};

/** @internal */
export const DownloadArtifactFolderRequest$outboundSchema: z.ZodType<
  DownloadArtifactFolderRequest$Outbound,
  z.ZodTypeDef,
  DownloadArtifactFolderRequest
> = z.object({
  path: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DownloadArtifactFolderRequest$ {
  /** @deprecated use `DownloadArtifactFolderRequest$inboundSchema` instead. */
  export const inboundSchema = DownloadArtifactFolderRequest$inboundSchema;
  /** @deprecated use `DownloadArtifactFolderRequest$outboundSchema` instead. */
  export const outboundSchema = DownloadArtifactFolderRequest$outboundSchema;
  /** @deprecated use `DownloadArtifactFolderRequest$Outbound` instead. */
  export type Outbound = DownloadArtifactFolderRequest$Outbound;
}

export function downloadArtifactFolderRequestToJSON(
  downloadArtifactFolderRequest: DownloadArtifactFolderRequest,
): string {
  return JSON.stringify(
    DownloadArtifactFolderRequest$outboundSchema.parse(
      downloadArtifactFolderRequest,
    ),
  );
}

export function downloadArtifactFolderRequestFromJSON(
  jsonString: string,
): SafeParseResult<DownloadArtifactFolderRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DownloadArtifactFolderRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DownloadArtifactFolderRequest' from JSON`,
  );
}
