/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DownloadRecordingRequest = {
  /**
   * The ID of the recording to download
   */
  id: string;
};

/** @internal */
export const DownloadRecordingRequest$inboundSchema: z.ZodType<
  DownloadRecordingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type DownloadRecordingRequest$Outbound = {
  id: string;
};

/** @internal */
export const DownloadRecordingRequest$outboundSchema: z.ZodType<
  DownloadRecordingRequest$Outbound,
  z.ZodTypeDef,
  DownloadRecordingRequest
> = z.object({
  id: z.string(),
});

export function downloadRecordingRequestToJSON(
  downloadRecordingRequest: DownloadRecordingRequest,
): string {
  return JSON.stringify(
    DownloadRecordingRequest$outboundSchema.parse(downloadRecordingRequest),
  );
}
export function downloadRecordingRequestFromJSON(
  jsonString: string,
): SafeParseResult<DownloadRecordingRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DownloadRecordingRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DownloadRecordingRequest' from JSON`,
  );
}
