/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DownloadArtifactFileRequest = {
  /**
   * Path to the file relative to .iris folder
   */
  path: string;
};

/** @internal */
export const DownloadArtifactFileRequest$inboundSchema: z.ZodType<
  DownloadArtifactFileRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  path: z.string(),
});
/** @internal */
export type DownloadArtifactFileRequest$Outbound = {
  path: string;
};

/** @internal */
export const DownloadArtifactFileRequest$outboundSchema: z.ZodType<
  DownloadArtifactFileRequest$Outbound,
  z.ZodTypeDef,
  DownloadArtifactFileRequest
> = z.object({
  path: z.string(),
});

export function downloadArtifactFileRequestToJSON(
  downloadArtifactFileRequest: DownloadArtifactFileRequest,
): string {
  return JSON.stringify(
    DownloadArtifactFileRequest$outboundSchema.parse(
      downloadArtifactFileRequest,
    ),
  );
}
export function downloadArtifactFileRequestFromJSON(
  jsonString: string,
): SafeParseResult<DownloadArtifactFileRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DownloadArtifactFileRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DownloadArtifactFileRequest' from JSON`,
  );
}
