/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ExecuteRpaStepsRequest = {
  id: string;
};

/** @internal */
export const ExecuteRpaStepsRequest$inboundSchema: z.ZodType<
  ExecuteRpaStepsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type ExecuteRpaStepsRequest$Outbound = {
  id: string;
};

/** @internal */
export const ExecuteRpaStepsRequest$outboundSchema: z.ZodType<
  ExecuteRpaStepsRequest$Outbound,
  z.ZodTypeDef,
  ExecuteRpaStepsRequest
> = z.object({
  id: z.string(),
});

export function executeRpaStepsRequestToJSON(
  executeRpaStepsRequest: ExecuteRpaStepsRequest,
): string {
  return JSON.stringify(
    ExecuteRpaStepsRequest$outboundSchema.parse(executeRpaStepsRequest),
  );
}
export function executeRpaStepsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ExecuteRpaStepsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExecuteRpaStepsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExecuteRpaStepsRequest' from JSON`,
  );
}
