/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAnalysisResultsRequest = {
  id: string;
};

/** @internal */
export const GetAnalysisResultsRequest$inboundSchema: z.ZodType<
  GetAnalysisResultsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type GetAnalysisResultsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetAnalysisResultsRequest$outboundSchema: z.ZodType<
  GetAnalysisResultsRequest$Outbound,
  z.ZodTypeDef,
  GetAnalysisResultsRequest
> = z.object({
  id: z.string(),
});

export function getAnalysisResultsRequestToJSON(
  getAnalysisResultsRequest: GetAnalysisResultsRequest,
): string {
  return JSON.stringify(
    GetAnalysisResultsRequest$outboundSchema.parse(getAnalysisResultsRequest),
  );
}
export function getAnalysisResultsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAnalysisResultsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAnalysisResultsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAnalysisResultsRequest' from JSON`,
  );
}
