/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAnalysisResultsRequest = {
  id: string;
};

/** @internal */
export const GetAnalysisResultsRequest$inboundSchema: z.ZodType<
  GetAnalysisResultsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetAnalysisResultsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetAnalysisResultsRequest$outboundSchema: z.ZodType<
  GetAnalysisResultsRequest$Outbound,
  z.ZodTypeDef,
  GetAnalysisResultsRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAnalysisResultsRequest$ {
  /** @deprecated use `GetAnalysisResultsRequest$inboundSchema` instead. */
  export const inboundSchema = GetAnalysisResultsRequest$inboundSchema;
  /** @deprecated use `GetAnalysisResultsRequest$outboundSchema` instead. */
  export const outboundSchema = GetAnalysisResultsRequest$outboundSchema;
  /** @deprecated use `GetAnalysisResultsRequest$Outbound` instead. */
  export type Outbound = GetAnalysisResultsRequest$Outbound;
}

export function getAnalysisResultsRequestToJSON(
  getAnalysisResultsRequest: GetAnalysisResultsRequest,
): string {
  return JSON.stringify(
    GetAnalysisResultsRequest$outboundSchema.parse(getAnalysisResultsRequest),
  );
}

export function getAnalysisResultsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAnalysisResultsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAnalysisResultsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAnalysisResultsRequest' from JSON`,
  );
}
