/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetExecutionStatusRequest = {
  /**
   * ID of the RPA execution to get status for
   */
  executionId: string;
};

/** @internal */
export const GetExecutionStatusRequest$inboundSchema: z.ZodType<
  GetExecutionStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  executionId: z.string(),
});

/** @internal */
export type GetExecutionStatusRequest$Outbound = {
  executionId: string;
};

/** @internal */
export const GetExecutionStatusRequest$outboundSchema: z.ZodType<
  GetExecutionStatusRequest$Outbound,
  z.ZodTypeDef,
  GetExecutionStatusRequest
> = z.object({
  executionId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetExecutionStatusRequest$ {
  /** @deprecated use `GetExecutionStatusRequest$inboundSchema` instead. */
  export const inboundSchema = GetExecutionStatusRequest$inboundSchema;
  /** @deprecated use `GetExecutionStatusRequest$outboundSchema` instead. */
  export const outboundSchema = GetExecutionStatusRequest$outboundSchema;
  /** @deprecated use `GetExecutionStatusRequest$Outbound` instead. */
  export type Outbound = GetExecutionStatusRequest$Outbound;
}

export function getExecutionStatusRequestToJSON(
  getExecutionStatusRequest: GetExecutionStatusRequest,
): string {
  return JSON.stringify(
    GetExecutionStatusRequest$outboundSchema.parse(getExecutionStatusRequest),
  );
}

export function getExecutionStatusRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetExecutionStatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetExecutionStatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetExecutionStatusRequest' from JSON`,
  );
}
