/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetFramesAndCaptionsRequest = {
  /**
   * The ID of the recording to get frames and captions for
   */
  id: string;
};

/** @internal */
export const GetFramesAndCaptionsRequest$inboundSchema: z.ZodType<
  GetFramesAndCaptionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type GetFramesAndCaptionsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetFramesAndCaptionsRequest$outboundSchema: z.ZodType<
  GetFramesAndCaptionsRequest$Outbound,
  z.ZodTypeDef,
  GetFramesAndCaptionsRequest
> = z.object({
  id: z.string(),
});

export function getFramesAndCaptionsRequestToJSON(
  getFramesAndCaptionsRequest: GetFramesAndCaptionsRequest,
): string {
  return JSON.stringify(
    GetFramesAndCaptionsRequest$outboundSchema.parse(
      getFramesAndCaptionsRequest,
    ),
  );
}
export function getFramesAndCaptionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetFramesAndCaptionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFramesAndCaptionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFramesAndCaptionsRequest' from JSON`,
  );
}
