/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetFramesAndCaptionsRequest = {
  /**
   * The ID of the recording to get frames and captions for
   */
  id: string;
};

/** @internal */
export const GetFramesAndCaptionsRequest$inboundSchema: z.ZodType<
  GetFramesAndCaptionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetFramesAndCaptionsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetFramesAndCaptionsRequest$outboundSchema: z.ZodType<
  GetFramesAndCaptionsRequest$Outbound,
  z.ZodTypeDef,
  GetFramesAndCaptionsRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetFramesAndCaptionsRequest$ {
  /** @deprecated use `GetFramesAndCaptionsRequest$inboundSchema` instead. */
  export const inboundSchema = GetFramesAndCaptionsRequest$inboundSchema;
  /** @deprecated use `GetFramesAndCaptionsRequest$outboundSchema` instead. */
  export const outboundSchema = GetFramesAndCaptionsRequest$outboundSchema;
  /** @deprecated use `GetFramesAndCaptionsRequest$Outbound` instead. */
  export type Outbound = GetFramesAndCaptionsRequest$Outbound;
}

export function getFramesAndCaptionsRequestToJSON(
  getFramesAndCaptionsRequest: GetFramesAndCaptionsRequest,
): string {
  return JSON.stringify(
    GetFramesAndCaptionsRequest$outboundSchema.parse(
      getFramesAndCaptionsRequest,
    ),
  );
}

export function getFramesAndCaptionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetFramesAndCaptionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFramesAndCaptionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFramesAndCaptionsRequest' from JSON`,
  );
}
