/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetFileInfoRequest = {
  /**
   * File ID
   */
  id: string;
};

/** @internal */
export const GetFileInfoRequest$inboundSchema: z.ZodType<
  GetFileInfoRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type GetFileInfoRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetFileInfoRequest$outboundSchema: z.ZodType<
  GetFileInfoRequest$Outbound,
  z.ZodTypeDef,
  GetFileInfoRequest
> = z.object({
  id: z.string(),
});

export function getFileInfoRequestToJSON(
  getFileInfoRequest: GetFileInfoRequest,
): string {
  return JSON.stringify(
    GetFileInfoRequest$outboundSchema.parse(getFileInfoRequest),
  );
}
export function getFileInfoRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetFileInfoRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFileInfoRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFileInfoRequest' from JSON`,
  );
}
