/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetFileInfoRequest = {
  /**
   * File ID
   */
  id: string;
};

/** @internal */
export const GetFileInfoRequest$inboundSchema: z.ZodType<
  GetFileInfoRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetFileInfoRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetFileInfoRequest$outboundSchema: z.ZodType<
  GetFileInfoRequest$Outbound,
  z.ZodTypeDef,
  GetFileInfoRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetFileInfoRequest$ {
  /** @deprecated use `GetFileInfoRequest$inboundSchema` instead. */
  export const inboundSchema = GetFileInfoRequest$inboundSchema;
  /** @deprecated use `GetFileInfoRequest$outboundSchema` instead. */
  export const outboundSchema = GetFileInfoRequest$outboundSchema;
  /** @deprecated use `GetFileInfoRequest$Outbound` instead. */
  export type Outbound = GetFileInfoRequest$Outbound;
}

export function getFileInfoRequestToJSON(
  getFileInfoRequest: GetFileInfoRequest,
): string {
  return JSON.stringify(
    GetFileInfoRequest$outboundSchema.parse(getFileInfoRequest),
  );
}

export function getFileInfoRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetFileInfoRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFileInfoRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFileInfoRequest' from JSON`,
  );
}
