/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetParameterTemplateRequest = {
  /**
   * ID of the recording to get parameter template for
   */
  recordingId: string;
};

/** @internal */
export const GetParameterTemplateRequest$inboundSchema: z.ZodType<
  GetParameterTemplateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  recordingId: z.string(),
});
/** @internal */
export type GetParameterTemplateRequest$Outbound = {
  recordingId: string;
};

/** @internal */
export const GetParameterTemplateRequest$outboundSchema: z.ZodType<
  GetParameterTemplateRequest$Outbound,
  z.ZodTypeDef,
  GetParameterTemplateRequest
> = z.object({
  recordingId: z.string(),
});

export function getParameterTemplateRequestToJSON(
  getParameterTemplateRequest: GetParameterTemplateRequest,
): string {
  return JSON.stringify(
    GetParameterTemplateRequest$outboundSchema.parse(
      getParameterTemplateRequest,
    ),
  );
}
export function getParameterTemplateRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetParameterTemplateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetParameterTemplateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetParameterTemplateRequest' from JSON`,
  );
}
