/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetParameterTemplateRequest = {
  /**
   * ID of the recording to get parameter template for
   */
  recordingId: string;
};

/** @internal */
export const GetParameterTemplateRequest$inboundSchema: z.ZodType<
  GetParameterTemplateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  recordingId: z.string(),
});

/** @internal */
export type GetParameterTemplateRequest$Outbound = {
  recordingId: string;
};

/** @internal */
export const GetParameterTemplateRequest$outboundSchema: z.ZodType<
  GetParameterTemplateRequest$Outbound,
  z.ZodTypeDef,
  GetParameterTemplateRequest
> = z.object({
  recordingId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetParameterTemplateRequest$ {
  /** @deprecated use `GetParameterTemplateRequest$inboundSchema` instead. */
  export const inboundSchema = GetParameterTemplateRequest$inboundSchema;
  /** @deprecated use `GetParameterTemplateRequest$outboundSchema` instead. */
  export const outboundSchema = GetParameterTemplateRequest$outboundSchema;
  /** @deprecated use `GetParameterTemplateRequest$Outbound` instead. */
  export type Outbound = GetParameterTemplateRequest$Outbound;
}

export function getParameterTemplateRequestToJSON(
  getParameterTemplateRequest: GetParameterTemplateRequest,
): string {
  return JSON.stringify(
    GetParameterTemplateRequest$outboundSchema.parse(
      getParameterTemplateRequest,
    ),
  );
}

export function getParameterTemplateRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetParameterTemplateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetParameterTemplateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetParameterTemplateRequest' from JSON`,
  );
}
