/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetRecordingThumbnailRequest = {
  /**
   * The ID of the recording to get the thumbnail for
   */
  id: string;
};

/** @internal */
export const GetRecordingThumbnailRequest$inboundSchema: z.ZodType<
  GetRecordingThumbnailRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetRecordingThumbnailRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetRecordingThumbnailRequest$outboundSchema: z.ZodType<
  GetRecordingThumbnailRequest$Outbound,
  z.ZodTypeDef,
  GetRecordingThumbnailRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRecordingThumbnailRequest$ {
  /** @deprecated use `GetRecordingThumbnailRequest$inboundSchema` instead. */
  export const inboundSchema = GetRecordingThumbnailRequest$inboundSchema;
  /** @deprecated use `GetRecordingThumbnailRequest$outboundSchema` instead. */
  export const outboundSchema = GetRecordingThumbnailRequest$outboundSchema;
  /** @deprecated use `GetRecordingThumbnailRequest$Outbound` instead. */
  export type Outbound = GetRecordingThumbnailRequest$Outbound;
}

export function getRecordingThumbnailRequestToJSON(
  getRecordingThumbnailRequest: GetRecordingThumbnailRequest,
): string {
  return JSON.stringify(
    GetRecordingThumbnailRequest$outboundSchema.parse(
      getRecordingThumbnailRequest,
    ),
  );
}

export function getRecordingThumbnailRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetRecordingThumbnailRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRecordingThumbnailRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRecordingThumbnailRequest' from JSON`,
  );
}
