/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetRecordingMetadataRequest = {
  /**
   * The ID of the recording to retrieve
   */
  id: string;
};

/** @internal */
export const GetRecordingMetadataRequest$inboundSchema: z.ZodType<
  GetRecordingMetadataRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetRecordingMetadataRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetRecordingMetadataRequest$outboundSchema: z.ZodType<
  GetRecordingMetadataRequest$Outbound,
  z.ZodTypeDef,
  GetRecordingMetadataRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRecordingMetadataRequest$ {
  /** @deprecated use `GetRecordingMetadataRequest$inboundSchema` instead. */
  export const inboundSchema = GetRecordingMetadataRequest$inboundSchema;
  /** @deprecated use `GetRecordingMetadataRequest$outboundSchema` instead. */
  export const outboundSchema = GetRecordingMetadataRequest$outboundSchema;
  /** @deprecated use `GetRecordingMetadataRequest$Outbound` instead. */
  export type Outbound = GetRecordingMetadataRequest$Outbound;
}

export function getRecordingMetadataRequestToJSON(
  getRecordingMetadataRequest: GetRecordingMetadataRequest,
): string {
  return JSON.stringify(
    GetRecordingMetadataRequest$outboundSchema.parse(
      getRecordingMetadataRequest,
    ),
  );
}

export function getRecordingMetadataRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetRecordingMetadataRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRecordingMetadataRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRecordingMetadataRequest' from JSON`,
  );
}
