/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListArtifactsRequest = {
  /**
   * Path relative to .iris folder
   */
  path?: string | undefined;
};

/** @internal */
export const ListArtifactsRequest$inboundSchema: z.ZodType<
  ListArtifactsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  path: z.string().optional(),
});
/** @internal */
export type ListArtifactsRequest$Outbound = {
  path?: string | undefined;
};

/** @internal */
export const ListArtifactsRequest$outboundSchema: z.ZodType<
  ListArtifactsRequest$Outbound,
  z.ZodTypeDef,
  ListArtifactsRequest
> = z.object({
  path: z.string().optional(),
});

export function listArtifactsRequestToJSON(
  listArtifactsRequest: ListArtifactsRequest,
): string {
  return JSON.stringify(
    ListArtifactsRequest$outboundSchema.parse(listArtifactsRequest),
  );
}
export function listArtifactsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListArtifactsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListArtifactsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListArtifactsRequest' from JSON`,
  );
}
