/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RegenerateVideoRequest = {
  /**
   * The ID of the recording to regenerate video for
   */
  id: string;
};

/** @internal */
export const RegenerateVideoRequest$inboundSchema: z.ZodType<
  RegenerateVideoRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type RegenerateVideoRequest$Outbound = {
  id: string;
};

/** @internal */
export const RegenerateVideoRequest$outboundSchema: z.ZodType<
  RegenerateVideoRequest$Outbound,
  z.ZodTypeDef,
  RegenerateVideoRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RegenerateVideoRequest$ {
  /** @deprecated use `RegenerateVideoRequest$inboundSchema` instead. */
  export const inboundSchema = RegenerateVideoRequest$inboundSchema;
  /** @deprecated use `RegenerateVideoRequest$outboundSchema` instead. */
  export const outboundSchema = RegenerateVideoRequest$outboundSchema;
  /** @deprecated use `RegenerateVideoRequest$Outbound` instead. */
  export type Outbound = RegenerateVideoRequest$Outbound;
}

export function regenerateVideoRequestToJSON(
  regenerateVideoRequest: RegenerateVideoRequest,
): string {
  return JSON.stringify(
    RegenerateVideoRequest$outboundSchema.parse(regenerateVideoRequest),
  );
}

export function regenerateVideoRequestFromJSON(
  jsonString: string,
): SafeParseResult<RegenerateVideoRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RegenerateVideoRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RegenerateVideoRequest' from JSON`,
  );
}
