/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type StreamOriginalVideoRequest = {
  filename: string;
};

/** @internal */
export const StreamOriginalVideoRequest$inboundSchema: z.ZodType<
  StreamOriginalVideoRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  filename: z.string(),
});
/** @internal */
export type StreamOriginalVideoRequest$Outbound = {
  filename: string;
};

/** @internal */
export const StreamOriginalVideoRequest$outboundSchema: z.ZodType<
  StreamOriginalVideoRequest$Outbound,
  z.ZodTypeDef,
  StreamOriginalVideoRequest
> = z.object({
  filename: z.string(),
});

export function streamOriginalVideoRequestToJSON(
  streamOriginalVideoRequest: StreamOriginalVideoRequest,
): string {
  return JSON.stringify(
    StreamOriginalVideoRequest$outboundSchema.parse(streamOriginalVideoRequest),
  );
}
export function streamOriginalVideoRequestFromJSON(
  jsonString: string,
): SafeParseResult<StreamOriginalVideoRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamOriginalVideoRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamOriginalVideoRequest' from JSON`,
  );
}
