/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type StreamProcessedVideoRequest = {
  filename: string;
};

/** @internal */
export const StreamProcessedVideoRequest$inboundSchema: z.ZodType<
  StreamProcessedVideoRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  filename: z.string(),
});

/** @internal */
export type StreamProcessedVideoRequest$Outbound = {
  filename: string;
};

/** @internal */
export const StreamProcessedVideoRequest$outboundSchema: z.ZodType<
  StreamProcessedVideoRequest$Outbound,
  z.ZodTypeDef,
  StreamProcessedVideoRequest
> = z.object({
  filename: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StreamProcessedVideoRequest$ {
  /** @deprecated use `StreamProcessedVideoRequest$inboundSchema` instead. */
  export const inboundSchema = StreamProcessedVideoRequest$inboundSchema;
  /** @deprecated use `StreamProcessedVideoRequest$outboundSchema` instead. */
  export const outboundSchema = StreamProcessedVideoRequest$outboundSchema;
  /** @deprecated use `StreamProcessedVideoRequest$Outbound` instead. */
  export type Outbound = StreamProcessedVideoRequest$Outbound;
}

export function streamProcessedVideoRequestToJSON(
  streamProcessedVideoRequest: StreamProcessedVideoRequest,
): string {
  return JSON.stringify(
    StreamProcessedVideoRequest$outboundSchema.parse(
      streamProcessedVideoRequest,
    ),
  );
}

export function streamProcessedVideoRequestFromJSON(
  jsonString: string,
): SafeParseResult<StreamProcessedVideoRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamProcessedVideoRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamProcessedVideoRequest' from JSON`,
  );
}
