/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Conversation object containing the caption text and metadata
 */
export type Conversation = {};

export type CaptionDataDto = {
  /**
   * Timestamp when the caption was created
   */
  timestamp: number;
  /**
   * Conversation object containing the caption text and metadata
   */
  conversation: Conversation;
  /**
   * The index of the frame this caption belongs to
   */
  frameIndex: number;
};

/** @internal */
export const Conversation$inboundSchema: z.ZodType<
  Conversation,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type Conversation$Outbound = {};

/** @internal */
export const Conversation$outboundSchema: z.ZodType<
  Conversation$Outbound,
  z.ZodTypeDef,
  Conversation
> = z.object({});

export function conversationToJSON(conversation: Conversation): string {
  return JSON.stringify(Conversation$outboundSchema.parse(conversation));
}
export function conversationFromJSON(
  jsonString: string,
): SafeParseResult<Conversation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Conversation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Conversation' from JSON`,
  );
}

/** @internal */
export const CaptionDataDto$inboundSchema: z.ZodType<
  CaptionDataDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  timestamp: z.number(),
  conversation: z.lazy(() => Conversation$inboundSchema),
  frameIndex: z.number(),
});
/** @internal */
export type CaptionDataDto$Outbound = {
  timestamp: number;
  conversation: Conversation$Outbound;
  frameIndex: number;
};

/** @internal */
export const CaptionDataDto$outboundSchema: z.ZodType<
  CaptionDataDto$Outbound,
  z.ZodTypeDef,
  CaptionDataDto
> = z.object({
  timestamp: z.number(),
  conversation: z.lazy(() => Conversation$outboundSchema),
  frameIndex: z.number(),
});

export function captionDataDtoToJSON(captionDataDto: CaptionDataDto): string {
  return JSON.stringify(CaptionDataDto$outboundSchema.parse(captionDataDto));
}
export function captionDataDtoFromJSON(
  jsonString: string,
): SafeParseResult<CaptionDataDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CaptionDataDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CaptionDataDto' from JSON`,
  );
}
