/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteRecordingResponseDto = {
  /**
   * Whether the delete operation was successful
   */
  success: boolean;
};

/** @internal */
export const DeleteRecordingResponseDto$inboundSchema: z.ZodType<
  DeleteRecordingResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
});

/** @internal */
export type DeleteRecordingResponseDto$Outbound = {
  success: boolean;
};

/** @internal */
export const DeleteRecordingResponseDto$outboundSchema: z.ZodType<
  DeleteRecordingResponseDto$Outbound,
  z.ZodTypeDef,
  DeleteRecordingResponseDto
> = z.object({
  success: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteRecordingResponseDto$ {
  /** @deprecated use `DeleteRecordingResponseDto$inboundSchema` instead. */
  export const inboundSchema = DeleteRecordingResponseDto$inboundSchema;
  /** @deprecated use `DeleteRecordingResponseDto$outboundSchema` instead. */
  export const outboundSchema = DeleteRecordingResponseDto$outboundSchema;
  /** @deprecated use `DeleteRecordingResponseDto$Outbound` instead. */
  export type Outbound = DeleteRecordingResponseDto$Outbound;
}

export function deleteRecordingResponseDtoToJSON(
  deleteRecordingResponseDto: DeleteRecordingResponseDto,
): string {
  return JSON.stringify(
    DeleteRecordingResponseDto$outboundSchema.parse(deleteRecordingResponseDto),
  );
}

export function deleteRecordingResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<DeleteRecordingResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteRecordingResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteRecordingResponseDto' from JSON`,
  );
}
