/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteRecordingResponseDto = {
  /**
   * Whether the delete operation was successful
   */
  success: boolean;
};

/** @internal */
export const DeleteRecordingResponseDto$inboundSchema: z.ZodType<
  DeleteRecordingResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
});
/** @internal */
export type DeleteRecordingResponseDto$Outbound = {
  success: boolean;
};

/** @internal */
export const DeleteRecordingResponseDto$outboundSchema: z.ZodType<
  DeleteRecordingResponseDto$Outbound,
  z.ZodTypeDef,
  DeleteRecordingResponseDto
> = z.object({
  success: z.boolean(),
});

export function deleteRecordingResponseDtoToJSON(
  deleteRecordingResponseDto: DeleteRecordingResponseDto,
): string {
  return JSON.stringify(
    DeleteRecordingResponseDto$outboundSchema.parse(deleteRecordingResponseDto),
  );
}
export function deleteRecordingResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<DeleteRecordingResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteRecordingResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteRecordingResponseDto' from JSON`,
  );
}
