/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FileInfoDto = {
  /**
   * Unique ID for the file
   */
  fileId: string;
  /**
   * The filename with timestamp
   */
  fileName: string;
  /**
   * The full file path
   */
  filePath: string;
  /**
   * URL to access the file
   */
  fileUrl: string;
  /**
   * Size of the file in bytes
   */
  fileSize: number;
  /**
   * MIME type of the file
   */
  mimeType: string;
  /**
   * File upload date
   */
  uploadDate: string;
};

/** @internal */
export const FileInfoDto$inboundSchema: z.ZodType<
  FileInfoDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  fileId: z.string(),
  fileName: z.string(),
  filePath: z.string(),
  fileUrl: z.string(),
  fileSize: z.number(),
  mimeType: z.string(),
  uploadDate: z.string(),
});

/** @internal */
export type FileInfoDto$Outbound = {
  fileId: string;
  fileName: string;
  filePath: string;
  fileUrl: string;
  fileSize: number;
  mimeType: string;
  uploadDate: string;
};

/** @internal */
export const FileInfoDto$outboundSchema: z.ZodType<
  FileInfoDto$Outbound,
  z.ZodTypeDef,
  FileInfoDto
> = z.object({
  fileId: z.string(),
  fileName: z.string(),
  filePath: z.string(),
  fileUrl: z.string(),
  fileSize: z.number(),
  mimeType: z.string(),
  uploadDate: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileInfoDto$ {
  /** @deprecated use `FileInfoDto$inboundSchema` instead. */
  export const inboundSchema = FileInfoDto$inboundSchema;
  /** @deprecated use `FileInfoDto$outboundSchema` instead. */
  export const outboundSchema = FileInfoDto$outboundSchema;
  /** @deprecated use `FileInfoDto$Outbound` instead. */
  export type Outbound = FileInfoDto$Outbound;
}

export function fileInfoDtoToJSON(fileInfoDto: FileInfoDto): string {
  return JSON.stringify(FileInfoDto$outboundSchema.parse(fileInfoDto));
}

export function fileInfoDtoFromJSON(
  jsonString: string,
): SafeParseResult<FileInfoDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileInfoDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileInfoDto' from JSON`,
  );
}
