/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  VideoRecordingDto,
  VideoRecordingDto$inboundSchema,
  VideoRecordingDto$Outbound,
  VideoRecordingDto$outboundSchema,
} from "./videorecordingdto.js";

export type RecordingListResponseDto = {
  /**
   * List of recordings
   */
  recordings: Array<VideoRecordingDto>;
};

/** @internal */
export const RecordingListResponseDto$inboundSchema: z.ZodType<
  RecordingListResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  recordings: z.array(VideoRecordingDto$inboundSchema),
});
/** @internal */
export type RecordingListResponseDto$Outbound = {
  recordings: Array<VideoRecordingDto$Outbound>;
};

/** @internal */
export const RecordingListResponseDto$outboundSchema: z.ZodType<
  RecordingListResponseDto$Outbound,
  z.ZodTypeDef,
  RecordingListResponseDto
> = z.object({
  recordings: z.array(VideoRecordingDto$outboundSchema),
});

export function recordingListResponseDtoToJSON(
  recordingListResponseDto: RecordingListResponseDto,
): string {
  return JSON.stringify(
    RecordingListResponseDto$outboundSchema.parse(recordingListResponseDto),
  );
}
export function recordingListResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<RecordingListResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RecordingListResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RecordingListResponseDto' from JSON`,
  );
}
