/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Operator type used for the session
 */
export const SaveSessionRecordingResponseDtoOperatorType = {
  Browser: "browser",
  Computer: "computer",
} as const;
/**
 * Operator type used for the session
 */
export type SaveSessionRecordingResponseDtoOperatorType = ClosedEnum<
  typeof SaveSessionRecordingResponseDtoOperatorType
>;

/**
 * Status of video generation
 */
export const SaveSessionRecordingResponseDtoVideoGenerationStatus = {
  Pending: "pending",
  InProgress: "in_progress",
  Completed: "completed",
  Failed: "failed",
} as const;
/**
 * Status of video generation
 */
export type SaveSessionRecordingResponseDtoVideoGenerationStatus = ClosedEnum<
  typeof SaveSessionRecordingResponseDtoVideoGenerationStatus
>;

/**
 * Recording metadata
 */
export type SaveSessionRecordingResponseDtoRecording = {
  /**
   * Unique identifier for the recording
   */
  id: string;
  /**
   * Session ID this recording belongs to
   */
  sessionId: string;
  /**
   * Title of the recording
   */
  title: string;
  /**
   * Description of the recording
   */
  description?: string | undefined;
  /**
   * Timestamp when the recording was created
   */
  createdAt: number;
  /**
   * Duration of the recording in milliseconds
   */
  duration: number;
  /**
   * Number of frames in the recording
   */
  frameCount: number;
  /**
   * Path to the thumbnail image
   */
  thumbnailPath?: string | undefined;
  /**
   * Path to the recording files
   */
  filePath: string;
  /**
   * Size of the recording in bytes
   */
  size: number;
  /**
   * Operator type used for the session
   */
  operatorType?: SaveSessionRecordingResponseDtoOperatorType | undefined;
  /**
   * Status of video generation
   */
  videoGenerationStatus?:
    | SaveSessionRecordingResponseDtoVideoGenerationStatus
    | undefined;
  /**
   * Timestamp when video generation started
   */
  videoGenerationStartedAt?: number | undefined;
  /**
   * Timestamp when video generation completed
   */
  videoGenerationCompletedAt?: number | undefined;
  /**
   * Error message if video generation failed
   */
  videoGenerationError?: string | undefined;
  /**
   * Whether the recording has a video
   */
  hasVideo?: boolean | undefined;
  /**
   * Path to the generated video file
   */
  videoPath?: string | undefined;
  /**
   * Format of the generated video
   */
  videoFormat?: string | undefined;
  /**
   * Size of the generated video in bytes
   */
  videoSize?: number | undefined;
  additionalProperties: { [k: string]: any };
};

export type SaveSessionRecordingResponseDto = {
  /**
   * Whether the request was successful
   */
  success: boolean;
  /**
   * Recording metadata
   */
  recording: SaveSessionRecordingResponseDtoRecording;
};

/** @internal */
export const SaveSessionRecordingResponseDtoOperatorType$inboundSchema:
  z.ZodNativeEnum<typeof SaveSessionRecordingResponseDtoOperatorType> = z
    .nativeEnum(SaveSessionRecordingResponseDtoOperatorType);

/** @internal */
export const SaveSessionRecordingResponseDtoOperatorType$outboundSchema:
  z.ZodNativeEnum<typeof SaveSessionRecordingResponseDtoOperatorType> =
    SaveSessionRecordingResponseDtoOperatorType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SaveSessionRecordingResponseDtoOperatorType$ {
  /** @deprecated use `SaveSessionRecordingResponseDtoOperatorType$inboundSchema` instead. */
  export const inboundSchema =
    SaveSessionRecordingResponseDtoOperatorType$inboundSchema;
  /** @deprecated use `SaveSessionRecordingResponseDtoOperatorType$outboundSchema` instead. */
  export const outboundSchema =
    SaveSessionRecordingResponseDtoOperatorType$outboundSchema;
}

/** @internal */
export const SaveSessionRecordingResponseDtoVideoGenerationStatus$inboundSchema:
  z.ZodNativeEnum<typeof SaveSessionRecordingResponseDtoVideoGenerationStatus> =
    z.nativeEnum(SaveSessionRecordingResponseDtoVideoGenerationStatus);

/** @internal */
export const SaveSessionRecordingResponseDtoVideoGenerationStatus$outboundSchema:
  z.ZodNativeEnum<typeof SaveSessionRecordingResponseDtoVideoGenerationStatus> =
    SaveSessionRecordingResponseDtoVideoGenerationStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SaveSessionRecordingResponseDtoVideoGenerationStatus$ {
  /** @deprecated use `SaveSessionRecordingResponseDtoVideoGenerationStatus$inboundSchema` instead. */
  export const inboundSchema =
    SaveSessionRecordingResponseDtoVideoGenerationStatus$inboundSchema;
  /** @deprecated use `SaveSessionRecordingResponseDtoVideoGenerationStatus$outboundSchema` instead. */
  export const outboundSchema =
    SaveSessionRecordingResponseDtoVideoGenerationStatus$outboundSchema;
}

/** @internal */
export const SaveSessionRecordingResponseDtoRecording$inboundSchema: z.ZodType<
  SaveSessionRecordingResponseDtoRecording,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    id: z.string(),
    sessionId: z.string(),
    title: z.string(),
    description: z.string().optional(),
    createdAt: z.number(),
    duration: z.number(),
    frameCount: z.number(),
    thumbnailPath: z.string().optional(),
    filePath: z.string(),
    size: z.number(),
    operatorType: SaveSessionRecordingResponseDtoOperatorType$inboundSchema
      .optional(),
    videoGenerationStatus:
      SaveSessionRecordingResponseDtoVideoGenerationStatus$inboundSchema
        .optional(),
    videoGenerationStartedAt: z.number().optional(),
    videoGenerationCompletedAt: z.number().optional(),
    videoGenerationError: z.string().optional(),
    hasVideo: z.boolean().optional(),
    videoPath: z.string().optional(),
    videoFormat: z.string().optional(),
    videoSize: z.number().optional(),
  }).catchall(z.any()),
  "additionalProperties",
);

/** @internal */
export type SaveSessionRecordingResponseDtoRecording$Outbound = {
  id: string;
  sessionId: string;
  title: string;
  description?: string | undefined;
  createdAt: number;
  duration: number;
  frameCount: number;
  thumbnailPath?: string | undefined;
  filePath: string;
  size: number;
  operatorType?: string | undefined;
  videoGenerationStatus?: string | undefined;
  videoGenerationStartedAt?: number | undefined;
  videoGenerationCompletedAt?: number | undefined;
  videoGenerationError?: string | undefined;
  hasVideo?: boolean | undefined;
  videoPath?: string | undefined;
  videoFormat?: string | undefined;
  videoSize?: number | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const SaveSessionRecordingResponseDtoRecording$outboundSchema: z.ZodType<
  SaveSessionRecordingResponseDtoRecording$Outbound,
  z.ZodTypeDef,
  SaveSessionRecordingResponseDtoRecording
> = z.object({
  id: z.string(),
  sessionId: z.string(),
  title: z.string(),
  description: z.string().optional(),
  createdAt: z.number(),
  duration: z.number(),
  frameCount: z.number(),
  thumbnailPath: z.string().optional(),
  filePath: z.string(),
  size: z.number(),
  operatorType: SaveSessionRecordingResponseDtoOperatorType$outboundSchema
    .optional(),
  videoGenerationStatus:
    SaveSessionRecordingResponseDtoVideoGenerationStatus$outboundSchema
      .optional(),
  videoGenerationStartedAt: z.number().optional(),
  videoGenerationCompletedAt: z.number().optional(),
  videoGenerationError: z.string().optional(),
  hasVideo: z.boolean().optional(),
  videoPath: z.string().optional(),
  videoFormat: z.string().optional(),
  videoSize: z.number().optional(),
  additionalProperties: z.record(z.any()),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SaveSessionRecordingResponseDtoRecording$ {
  /** @deprecated use `SaveSessionRecordingResponseDtoRecording$inboundSchema` instead. */
  export const inboundSchema =
    SaveSessionRecordingResponseDtoRecording$inboundSchema;
  /** @deprecated use `SaveSessionRecordingResponseDtoRecording$outboundSchema` instead. */
  export const outboundSchema =
    SaveSessionRecordingResponseDtoRecording$outboundSchema;
  /** @deprecated use `SaveSessionRecordingResponseDtoRecording$Outbound` instead. */
  export type Outbound = SaveSessionRecordingResponseDtoRecording$Outbound;
}

export function saveSessionRecordingResponseDtoRecordingToJSON(
  saveSessionRecordingResponseDtoRecording:
    SaveSessionRecordingResponseDtoRecording,
): string {
  return JSON.stringify(
    SaveSessionRecordingResponseDtoRecording$outboundSchema.parse(
      saveSessionRecordingResponseDtoRecording,
    ),
  );
}

export function saveSessionRecordingResponseDtoRecordingFromJSON(
  jsonString: string,
): SafeParseResult<
  SaveSessionRecordingResponseDtoRecording,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SaveSessionRecordingResponseDtoRecording$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SaveSessionRecordingResponseDtoRecording' from JSON`,
  );
}

/** @internal */
export const SaveSessionRecordingResponseDto$inboundSchema: z.ZodType<
  SaveSessionRecordingResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  recording: z.lazy(() =>
    SaveSessionRecordingResponseDtoRecording$inboundSchema
  ),
});

/** @internal */
export type SaveSessionRecordingResponseDto$Outbound = {
  success: boolean;
  recording: SaveSessionRecordingResponseDtoRecording$Outbound;
};

/** @internal */
export const SaveSessionRecordingResponseDto$outboundSchema: z.ZodType<
  SaveSessionRecordingResponseDto$Outbound,
  z.ZodTypeDef,
  SaveSessionRecordingResponseDto
> = z.object({
  success: z.boolean(),
  recording: z.lazy(() =>
    SaveSessionRecordingResponseDtoRecording$outboundSchema
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SaveSessionRecordingResponseDto$ {
  /** @deprecated use `SaveSessionRecordingResponseDto$inboundSchema` instead. */
  export const inboundSchema = SaveSessionRecordingResponseDto$inboundSchema;
  /** @deprecated use `SaveSessionRecordingResponseDto$outboundSchema` instead. */
  export const outboundSchema = SaveSessionRecordingResponseDto$outboundSchema;
  /** @deprecated use `SaveSessionRecordingResponseDto$Outbound` instead. */
  export type Outbound = SaveSessionRecordingResponseDto$Outbound;
}

export function saveSessionRecordingResponseDtoToJSON(
  saveSessionRecordingResponseDto: SaveSessionRecordingResponseDto,
): string {
  return JSON.stringify(
    SaveSessionRecordingResponseDto$outboundSchema.parse(
      saveSessionRecordingResponseDto,
    ),
  );
}

export function saveSessionRecordingResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<SaveSessionRecordingResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SaveSessionRecordingResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SaveSessionRecordingResponseDto' from JSON`,
  );
}
