/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SimpleSuccessResponseDto = {
  /**
   * Whether the operation was successful
   */
  success: boolean;
  /**
   * Optional message with additional details
   */
  message?: string | undefined;
};

/** @internal */
export const SimpleSuccessResponseDto$inboundSchema: z.ZodType<
  SimpleSuccessResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  message: z.string().optional(),
});
/** @internal */
export type SimpleSuccessResponseDto$Outbound = {
  success: boolean;
  message?: string | undefined;
};

/** @internal */
export const SimpleSuccessResponseDto$outboundSchema: z.ZodType<
  SimpleSuccessResponseDto$Outbound,
  z.ZodTypeDef,
  SimpleSuccessResponseDto
> = z.object({
  success: z.boolean(),
  message: z.string().optional(),
});

export function simpleSuccessResponseDtoToJSON(
  simpleSuccessResponseDto: SimpleSuccessResponseDto,
): string {
  return JSON.stringify(
    SimpleSuccessResponseDto$outboundSchema.parse(simpleSuccessResponseDto),
  );
}
export function simpleSuccessResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<SimpleSuccessResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SimpleSuccessResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SimpleSuccessResponseDto' from JSON`,
  );
}
