/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SuccessResponseDto = {
  /**
   * Whether the operation was successful
   */
  success: boolean;
};

/** @internal */
export const SuccessResponseDto$inboundSchema: z.ZodType<
  SuccessResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
});
/** @internal */
export type SuccessResponseDto$Outbound = {
  success: boolean;
};

/** @internal */
export const SuccessResponseDto$outboundSchema: z.ZodType<
  SuccessResponseDto$Outbound,
  z.ZodTypeDef,
  SuccessResponseDto
> = z.object({
  success: z.boolean(),
});

export function successResponseDtoToJSON(
  successResponseDto: SuccessResponseDto,
): string {
  return JSON.stringify(
    SuccessResponseDto$outboundSchema.parse(successResponseDto),
  );
}
export function successResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<SuccessResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SuccessResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SuccessResponseDto' from JSON`,
  );
}
