/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SuccessResponseDto = {
  /**
   * Whether the operation was successful
   */
  success: boolean;
};

/** @internal */
export const SuccessResponseDto$inboundSchema: z.ZodType<
  SuccessResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
});

/** @internal */
export type SuccessResponseDto$Outbound = {
  success: boolean;
};

/** @internal */
export const SuccessResponseDto$outboundSchema: z.ZodType<
  SuccessResponseDto$Outbound,
  z.ZodTypeDef,
  SuccessResponseDto
> = z.object({
  success: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SuccessResponseDto$ {
  /** @deprecated use `SuccessResponseDto$inboundSchema` instead. */
  export const inboundSchema = SuccessResponseDto$inboundSchema;
  /** @deprecated use `SuccessResponseDto$outboundSchema` instead. */
  export const outboundSchema = SuccessResponseDto$outboundSchema;
  /** @deprecated use `SuccessResponseDto$Outbound` instead. */
  export type Outbound = SuccessResponseDto$Outbound;
}

export function successResponseDtoToJSON(
  successResponseDto: SuccessResponseDto,
): string {
  return JSON.stringify(
    SuccessResponseDto$outboundSchema.parse(successResponseDto),
  );
}

export function successResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<SuccessResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SuccessResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SuccessResponseDto' from JSON`,
  );
}
