/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { blobLikeSchema } from "../../types/blobs.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FileT = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type VideoUploadDto = {
  /**
   * Video file to analyze (MP4, WebM, or AVI)
   */
  file: FileT | Blob;
};

/** @internal */
export const FileT$inboundSchema: z.ZodType<FileT, z.ZodTypeDef, unknown> = z
  .object({
    fileName: z.string(),
    content: z.union([
      z.instanceof(ReadableStream<Uint8Array>),
      z.instanceof(Blob),
      z.instanceof(ArrayBuffer),
      z.instanceof(Uint8Array),
    ]),
  });

/** @internal */
export type FileT$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const FileT$outboundSchema: z.ZodType<
  FileT$Outbound,
  z.ZodTypeDef,
  FileT
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileT$ {
  /** @deprecated use `FileT$inboundSchema` instead. */
  export const inboundSchema = FileT$inboundSchema;
  /** @deprecated use `FileT$outboundSchema` instead. */
  export const outboundSchema = FileT$outboundSchema;
  /** @deprecated use `FileT$Outbound` instead. */
  export type Outbound = FileT$Outbound;
}

export function fileToJSON(fileT: FileT): string {
  return JSON.stringify(FileT$outboundSchema.parse(fileT));
}

export function fileFromJSON(
  jsonString: string,
): SafeParseResult<FileT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileT' from JSON`,
  );
}

/** @internal */
export const VideoUploadDto$inboundSchema: z.ZodType<
  VideoUploadDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  file: z.lazy(() => FileT$inboundSchema),
});

/** @internal */
export type VideoUploadDto$Outbound = {
  file: FileT$Outbound | Blob;
};

/** @internal */
export const VideoUploadDto$outboundSchema: z.ZodType<
  VideoUploadDto$Outbound,
  z.ZodTypeDef,
  VideoUploadDto
> = z.object({
  file: z.lazy(() => FileT$outboundSchema).or(blobLikeSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VideoUploadDto$ {
  /** @deprecated use `VideoUploadDto$inboundSchema` instead. */
  export const inboundSchema = VideoUploadDto$inboundSchema;
  /** @deprecated use `VideoUploadDto$outboundSchema` instead. */
  export const outboundSchema = VideoUploadDto$outboundSchema;
  /** @deprecated use `VideoUploadDto$Outbound` instead. */
  export type Outbound = VideoUploadDto$Outbound;
}

export function videoUploadDtoToJSON(videoUploadDto: VideoUploadDto): string {
  return JSON.stringify(VideoUploadDto$outboundSchema.parse(videoUploadDto));
}

export function videoUploadDtoFromJSON(
  jsonString: string,
): SafeParseResult<VideoUploadDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VideoUploadDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VideoUploadDto' from JSON`,
  );
}
