/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type VideoAnalysisResponseDto = {
  /**
   * Unique identifier for the analysis
   */
  analysisId: string;
  /**
   * Original uploaded video filename
   */
  originalVideo: string;
  /**
   * Processed video filename with idle sections removed
   */
  processedVideo: string;
  /**
   * Status message
   */
  message: string;
};

/** @internal */
export const VideoAnalysisResponseDto$inboundSchema: z.ZodType<
  VideoAnalysisResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  analysisId: z.string(),
  originalVideo: z.string(),
  processedVideo: z.string(),
  message: z.string(),
});
/** @internal */
export type VideoAnalysisResponseDto$Outbound = {
  analysisId: string;
  originalVideo: string;
  processedVideo: string;
  message: string;
};

/** @internal */
export const VideoAnalysisResponseDto$outboundSchema: z.ZodType<
  VideoAnalysisResponseDto$Outbound,
  z.ZodTypeDef,
  VideoAnalysisResponseDto
> = z.object({
  analysisId: z.string(),
  originalVideo: z.string(),
  processedVideo: z.string(),
  message: z.string(),
});

export function videoAnalysisResponseDtoToJSON(
  videoAnalysisResponseDto: VideoAnalysisResponseDto,
): string {
  return JSON.stringify(
    VideoAnalysisResponseDto$outboundSchema.parse(videoAnalysisResponseDto),
  );
}
export function videoAnalysisResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<VideoAnalysisResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VideoAnalysisResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VideoAnalysisResponseDto' from JSON`,
  );
}
